= Knative on minishift 

A derivative of official instructions of https://github.com/knative/docs/blob/master/install/Knative-with-OpenShift.md[Knative on OpenShift], which details on how to deploy https://cloud.google.com/knative/[Knative] on https://github.com/minishift/minishift[minishift].

[NOTE]
====
https://cloud.google.com/knative/[Knative] requires OpenShift 3.10.0 or above, hence its recommended to install latest https://github.com/minishift/minishift[minishift].
====

== minishift setup

[source,bash]
-----
#!/bin/bash

# add the location of minishift executable to PATH
# I also keep other handy tools like oc,kubectl, stern, kubectx
# in that directory

minishift profile set knative
minishift config set memory 8GB
minishift config set cpus 4
minishift config set image-caching true
minishift addon enable admin-user
minishift addon enable anyuid

minishift start

eval $(minishift docker-env) && eval $(minishift oc-env)
-----

=== Enable Admission and Validation hook

[IMPORTANT]
====
This is a work around until the next version of https://github.com/minishift/minishift[minishift] is released which allows to apply the patch with minishift command.
====

[source,bash]
----
#!/bin/bash
minishift ssh 
cp /var/lib/minishift/base/kube-apiserver/master-config.yaml /var/lib/minishift/base/kube-apiserver/master-config.yaml.old0
sed -i -e 's/"admissionConfig":{"pluginConfig":null}/"admissionConfig": {\
    "pluginConfig": {\
        "ValidatingAdmissionWebhook": {\
            "configuration": {\
                "apiVersion": "v1",\
                "kind": "DefaultAdmissionConfig",\
                "disable": false\
            }\
        },\
        "MutatingAdmissionWebhook": {\
            "configuration": {\
                "apiVersion": "v1",\
                "kind": "DefaultAdmissionConfig",\
                "disable": false\
            }\
        }\
    }\
}/' /var/lib/minishift/base/kube-apiserver/master-config.yaml

docker stop $(docker ps -l -q --filter "label=io.kubernetes.container.name=api") # <1>
----

<1> wait for some time after this step to allow OpenShift to be restarted automatically. e.g. you can try doing `oc login -u admin -p admin` until you are able to login again.

== Pre-requisites

https://docs.okd.io/3.10/admin_guide/manage_scc.html[SCCs (Security Context Constraints)] are the precursor to the PSP (Pod Security Policy) mechanism in Kubernetes.
[source,bash]
----
oc project myproject 
# Set privileged scc to default SA in myproject
oc adm policy add-scc-to-user privileged -z default
# Automatic Istio sidecar injection
oc label namespace myproject istio-injection=enabled
kubectl get namespace --show-labels  #<1>
----

<1> This should show the **myproject** namespace with **istio-injection=enabled** label

== Knative Deployment

You can clone the repository from https://github.com/redhat-developers-demo/knative-minishift.  For convenience we call the cloned folder as $PROJECT_HOME. 

==== Knative Istio

[source,bash]
----
cd $PROJECT_HOME
bin/istio_openshift_policies.sh  # <1>
curl -L https://storage.googleapis.com/knative-releases/serving/latest/istio.yaml \
  | sed 's/LoadBalancer/NodePort/' \
  | kubectl apply -f -
----

<1> This will setup the required OpenShift security policies that are required to deploy and make Istio functional

Wait until all the pods on istio-system are up and running, you can verify it with the command `oc get pods -w -n istio-system`.

[IMPORTANT]
=====
The Istio v1.0.1 release automatic sidecar injection has removed `privileged:true` from init contianers,this will cause the Pods with istio proxies automatic inject to crash. Run the following command to update the **istio-sidecar-injector** configmap

[sources,bash]
----
#/bin/bash

$ kubectl get cm istio-sidecar-injector -n istio-system -oyaml | sed -e 's/securityContext:/securityContext:\\n      privileged: true/' | kubectl replace -f -
----

Please run this command only once to avoid multiple additions
=====

==== Knative Serving

https://github.com/knative/serving[Knative Serving] supports deploying of serverless functions and applications on Kubernetes.

Assuming you are in $PROJECT_HOME,

[source,bash]
----
#/bin/bash

bin/knative_openshift_policies.sh # <1>

# Knative serving 
curl -L https://storage.googleapis.com/knative-releases/serving/latest/release-lite.yaml \
  | sed 's/LoadBalancer/NodePort/' \
  | kubectl apply -f -
----

<1> This will setup the required OpenShift security policies that are required to deploy and make Knative functional

Wait until all the pods in the knative-serving are up and running, you can verify it with the command `oc get pods -n knative-serving -w`.

== App Deployment 

=== Service
Lets now deploy an simple node.js application to make sure our deployment works,

[sources,bash]
-----

cd apps/kelloworld-nodejs

docker build -t dev.local/kelloworld:0.0.1 --rm .

kubectl apply -f service.yaml

export IP_ADDRESS=$(oc get node -o 'jsonpath={.items[0].status.addresses[0].address}'):$(oc get svc knative-ingressgateway -n istio-system -o 'jsonpath={.spec.ports[?(@.port==80)].nodePort}')

export HOST_URL=$(oc get  services.serving.knative.dev kelloworld  -o jsonpath='{.status.domain}')

curl -H "Host: ${HOST_URL}" http://${IP_ADDRESS}
-----

The curl above should return "Welcome Knative Serving on OpenShift".

NOTE: There is also utility script called `call.sh` inside $PROJECT_HOME/bin which can be used to call the functions.

If you'd like to view the available sample apps and deploy one of your choosing, head to the https://github.com/knative/docs/blob/master/serving/samples/README.md[sample apps] repo.

=== Canary

Cleanup all existing objects using the command:

[sources,bash]
----
#!bin/bash
kubectl delete all --all
cd $PROJECT_HOME/apps/kelloworld-nodejs/routing
kubectl apply -f app.yaml <1>
----

<1> In this case we will not use `service` object instead create the Knative serving objects individually.

==== Create a new version of the app 

Update the $PROJECT_HOME/apps/kelloworld-nodejs/app.js code to look like 

[sources,JavaScript]
----
var express = require('express');
var app = express();

const asciiart = require("ascii-art");
app.get("/", function (req, res, next) {
  asciiart.font("Knative", "Doom", (rendered) => {
    res.status(200).send(rendered);
  });
});

app.listen(8080,function() {
console.log("App started in port 8080");
});
----

Build a new image using the following command,
[sources,bash]
----
#!bin/bash
docker build -t dev.local/kelloworld:0.0.2 --rm .
----

Update the application configuration to create new revision:

[sources,bash]
----
#!bin/bash
kubectl apply -f config-v2.yaml <1>
----

<1> This should create a new revision e.g. `kelloworld-00002` 

Apply any one or more of the following routes to see the split of the traffic:

- all-rev1.yaml        -- All traffic to revision kelloworld-00001
- all-rev2.yaml        -- All traffic to revision kelloworld-00002
- rev1-rev2_50-50.yaml -- Traffic split 50-50 between kelloworld-00001 and kelloworld-00002

sources,bash]
----
#!bin/bash
kubectl apply -f rev1-rev2_50-50.yaml 
----


[TIP]
====
Run the script $PROJECT_HOME/bin/poll.sh on a new terminal and you can see changes to the output while applying the routes
====

== Clean up

[sources,bash]
-----

kubectl delete configurations.serving.knative.dev --all
kubectl delete revisions.serving.knative.dev --all
kubectl delete routes.serving.knative.dev --all
kubectl delete services.serving.knative.dev --all

(or)

kubectl delete all --all

-----
