= Knative on minishift 

This instructions helps you setup knative on minishift and deploy sample application.  This is a derivative of official instructions that can be found at https://github.com/knative/docs/blob/master/install/Knative-with-OpenShift.md

== minishift setup

[source,bash]
-----
#!/bin/bash

# add the location of minishift executable to PATH
# I also keep other handy tools like kubectl ,kubetail.sh, stern, kubectx
# in that directory

minishift profile set serverless
minishift config set memory 8GB
minishift config set cpus 4
minishift config set image-caching true
minishift addon enable admin-user
minishift addon enable anyuid

minishift start
-----

eval $(minishift docker-env) && eval $(minishift oc-env)

=== Enable Admission and Validation hook

[source,bash]
----
$minishift ssh 
$ cp /var/lib/minishift/base/kube-apiserver/master-config.yaml /var/lib/minishift/base/kube-apiserver/master-config.yaml.old0
$ sed -i -e 's/"admissionConfig":{"pluginConfig":null}/"admissionConfig": {\
    "pluginConfig": {\
        "ValidatingAdmissionWebhook": {\
            "configuration": {\
                "apiVersion": "v1",\
                "kind": "DefaultAdmissionConfig",\
                "disable": false\
            }\
        },\
        "MutatingAdmissionWebhook": {\
            "configuration": {\
                "apiVersion": "v1",\
                "kind": "DefaultAdmissionConfig",\
                "disable": false\
            }\
        }\
    }\
}/' /var/lib/minishift/base/kube-apiserver/master-config.yaml
----

minishift openshift config view

== Knative Setup

=== Pre-requisites

SCCs (Security Context Constraints) are the precursor to the PSP (Pod Security Policy) mechanism in Kubernetes.
[source,bash]
----
oc project myproject 
# Set privileged scc to default SA in myproject
oc adm policy add-scc-to-user privileged -z default
# Automatic Istio sidecar injection
oc label namespace myproject istio-injection=enabled
oc get namespace --show-labels
----

=== Istio Setup

[source,bash]
----

oc adm policy add-scc-to-user anyuid -z istio-ingress-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z default -n istio-system
oc adm policy add-scc-to-user anyuid -z prometheus -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-egressgateway-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-citadel-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-ingressgateway-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-cleanup-old-ca-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-mixer-post-install-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-mixer-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-pilot-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-sidecar-injector-service-account -n istio-system
oc adm policy add-cluster-role-to-user cluster-admin -z istio-galley-service-account -n istio-system

----

=== Knative 

==== Knative Istio

[source,bash]
----
curl -L https://storage.googleapis.com/knative-releases/serving/latest/istio.yaml \
  | sed 's/LoadBalancer/NodePort/' \
  | oc apply -f -
----

Wait until all the pods on istio-system are up and running, you can verify it with the command `oc get pods -w -n istio-system`

==== Knative Serving

[source,bash]
----

# OpenShift scc policy 

oc adm policy add-scc-to-user anyuid -z build-controller -n knative-build
oc adm policy add-scc-to-user anyuid -z controller -n knative-serving
oc adm policy add-scc-to-user anyuid -z autoscaler -n knative-serving
oc adm policy add-scc-to-user anyuid -z kube-state-metrics -n monitoring
oc adm policy add-scc-to-user anyuid -z node-exporter -n monitoring
oc adm policy add-scc-to-user anyuid -z prometheus-system -n monitoring
oc adm policy add-cluster-role-to-user cluster-admin -z build-controller -n knative-build
oc adm policy add-cluster-role-to-user cluster-admin -z controller -n knative-serving

# Knative serving 
curl -L https://storage.googleapis.com/knative-releases/serving/latest/release-lite.yaml \
  | sed 's/LoadBalancer/NodePort/' \
  | oc apply -f -
----

== Troubleshooting

The Service "knative-ingressgateway" is invalid: spec.ports[2].nodePort: Invalid value: 32400: provided port is already allocated
  
  Update the ingress-gateway of istio-system to 15301 nodeport to something other than 32400


